### ISSUE TITLE
Issues with making GET requests in my routers.

### ISSUE THREAD

**Issue by NyaYean** [Nyeanafehn/sublease#6]
@harimohanraj89 @bigtone1284 @WilliamfShaw 

Good Morning,

I need assistance in making a GET request to craigslist and including query parameters within the request. Currently, my code looks like this

``` js
listingRouter.get('/onelisting', function(req, res){
    var queryParams = req.query;
    request({
          url: 'http://newyork.craigslist.org/search/sub?',
          method: 'GET',
          json: true,
          qs: queryParams
    }, function(error, response, body) {
            var $ = cheerio.load(body);
            var body = [];
            var time = [];
            $('#postingbody').each(function(i, elem){
                body[i] = $(this).text();
            });
            $('.postinginfo, time').each(function(i, elem){
                time[i] = $(this).text();
            });
            console.log(body);
    });
})
```

I've tried testing it out and actually, not to sure on how to. Please assist. Thanks

**Comment by harimohanraj89** [comment]
Taken. Nya, we spoke about how to go about testing this code. Now that you are able to test, play around with it. If you run into follow-up problems, please comment here. Else go ahead and close this issue.
