### ISSUE TITLE
Having problems making post requests from my app.js file

### ISSUE THREAD

**Issue by NyaYean** [Nyeanafehn/sublease#7]
@harimohanraj89 @WilliamfShaw @DrRobotmck @bigtone1284 

Good Afternoon,

I am trying to make a post request from my app.js file. My code for making post request is listed below

var createUser = function(){
    $('#user-access').empty();
    $('#user-access').append(createUserTemplate)
    var name = $('#create-name').val()
    var username = $('#create-username').val()
    var sublease_term = $('#create-sublease-term').val()
    var move_in_date = $('#move-in-date').val()
    var location = $('#user-location').val()
    var password_digest = $('#login-password').val()

```
$('body').on('click','#create-button', function(){

    $.post('/user', {
        name: name,
        username: username,
        sublease_term: sublease_term,
        move_in_date: move_in_date,
        password_digest: password_digest,
        location: location
    })
    .done(function(){
        alert("Thank you for creating an account");
    })
    .fail(function(){
        alert('Please try again')
    })
})
```

}

I can make the requests in the console but when I try to do it using the values of the input boxes, I get model validation errors. Please assist. Thanks

**Comment by harimohanraj89** [comment]
You are grabbing the values before the user has entered them! Try grabbing the values of the input boxes **after** the user has clicked submit.

**Comment by NyaYean** [comment]
I think I got it now, thanks!!

**Comment by NyaYean** [comment]
Hey, I still having issues with the same problem. I solved some of the validation issues, but I have a few more that is popping up, even though the criteria for the information is correct. It seems that user input is being submitted through so I not sure what is going on

**Comment by NyaYean** [comment]
I got it working now. Thanks!!!
